# This workflow will install dependencies and run tests using invoke

name: CI with invoke

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: make install

    - name: Run tests
      run: make test

    - name: Prepprocess tests
      run: sed '0,/.*testsuite.*/s///' robot-report.xml | tac | sed '0,/.*testsuite.*/s///' | tac > temp.xml && mv temp.xml robot-report.xml && cat robot-report.xml

    - name: Test Report
      uses: dorny/test-reporter@v2
      if: always()
      with:
        name: Tests
        path: '**/*-report.xml'
        reporter: java-junit
 